### ISSUE TITLE
Levantamiento de Requisitos No funcionales

### ISSUE THREAD

**Issue by Tartaros24** [zetadevelopment/PMZ_Software#10]
En esta actividad se definirá con base en la problemática del cliente, y cada uno de los requisitos específicos ha cumplir dentro de la ejecución y creación de la solución.

Documentarlos en los comentarios y al tenerlos todos definidos pasarlos al formato de la IEEE.

**Comment by Tartaros24** [comment]
El sistema no deberá permitir logueos simultáneos con un mismo usuario.

**Comment by Tartaros24** [comment]
Se debe generar un backup de las BD semanalmente.

**Comment by Tartaros24** [comment]
Se podrá recuperar la contraseña de un usuario de forma segura.

**Comment by Tartaros24** [comment]
Se debe garantizar un 99,9% de disponibilidad del Internet.

**Comment by estebanz01** [comment]
El sistema deberá estar en español.

**Comment by estebanz01** [comment]
El sistema deberá ser compatible con navegadores Chrome y Firefox.

**Comment by estebanz01** [comment]
El sistema podrá instalarse en un servidor físico como en un sistema en la nube.

**Comment by estebanz01** [comment]
El sistema deberá ser funcional en sistemas móviles autorizados.
