### ISSUE TITLE
Diagrama de caso de uso

### ISSUE THREAD

**Issue by Tartaros24** [zetadevelopment/PMZ_Software#17]
Diagrama de caso de uso General del proyecto.

#19

**Comment by Tartaros24** [comment]
Se Anexa el link del archivo de Word donde se están generando los casos de Uso para cada Requerimiento funcional

https://docs.google.com/document/d/18yRYXfERrePQI-hIsuuFHHo93JjAxOBz_Mu2Ab7wEPU/edit?usp=sharing

**Comment by estebanz01** [comment]
https://docs.google.com/drawings/d/1VsWcMr_lEdDSJMMycF8mG3PVI5y4T6lXbPEoTEYh06s/

**Comment by estebanz01** [comment]
https://docs.google.com/drawings/d/1ZPAibD88Ks__6USb-XsepXMMy2QI6oc-xQL4cuUn4n
