### ISSUE TITLE
Objetivos

### ISSUE THREAD

**Issue by Tartaros24** [zetadevelopment/PMZ_Software#18]
**Objetivo General**

Implementar un software que permita integrar las actividades realizadas por la organización.

**Objetivos Específicos**

1. Recopilar las actividades realizadas por cada sede y registrarlas en el sistema.
2. Conectar en tiempo real los procedimientos de ventas, inventario y facturación de todas las sedes.
3. Tener un control de las actividades realizadas por empleado.
4. Generar informes de todas las actividades y los procedimientos realizados en cada una de ellas.
5. Controlar y monitorear los movimientos realizados en el sistema.

**Comment by estebanz01** [comment]
**Objetivo General:** Implementar un software que permita integrar las actividades que se realizan en la empresa _Maxitienda_.

**Comment by estebanz01** [comment]
**Objetivos específicos:**
* Automatizar ciertos procesos críticos de la empresa _Maxitienda_.
* Implementar procesos que faciliten el manejo de inventario.
* Implementar procesos que permitan tener conocimiento de las actividades laborales de los empleados.
* Generar alertas basadas en los inventarios registrados.

**Comment by Tartaros24** [comment]
- Automatizar los procesos críticos de la empresa Maxitienda
