### ISSUE TITLE
Documentación de los Casos de Uso

### ISSUE THREAD

**Issue by Tartaros24** [zetadevelopment/PMZ_Software#19]
Documentación de los casos de uso para cada requisito funcional.

#7 
#8 

https://docs.google.com/document/d/1oLJKUD_ZZJwrX8RIPXdvpW37MiNYg_X3lgJC-SzLGmI/edit

**Comment by estebanz01** [comment]
Realicé un cambio en el requisito **R-0001** para que esté acorde al flujo de datos presentado en el prototipo inicial y en el diagrama de flujo de datos. ✔️
