### ISSUE TITLE
Levantamiento de Requisitos funcionales

### ISSUE THREAD

**Issue by Tartaros24** [zetadevelopment/PMZ_Software#7]
En esta actividad se definirá con base en la problemática del cliente, y cada uno de los requisitos específicos ha cumplir dentro de la ejecución y creación de la solución.

Documentarlos en los comentarios y al tenerlos todos definidos pasarlos al formato de la IEEE.

**Comment by estebanz01** [comment]
Como cajero, debo poder registrar una venta en el sistema.

**Comment by estebanz01** [comment]
Como cliente, si no estoy registrado, puedo optar por registrarme en el sistema, a través del servicio ofrecido por el cajero.

**Comment by estebanz01** [comment]
Cuando una venta se registra, el inventario debe ser actualizado de forma automática.

**Comment by estebanz01** [comment]
Como empleado, debe tener un registro de todas las aperturas y cierres de caja realizadas durante el día.

**Comment by estebanz01** [comment]
Si mi producto está por debajo de un valor mínimo, el sistema debe generar una alerta.

**Comment by estebanz01** [comment]
Toda actividad realizada en el sistema, debe quedar asociada a un empleado

**Comment by estebanz01** [comment]
Sólo se podrá permitir el uso del sistema a empleados previamente identificados utilizando algún método seguro.

**Comment by Tartaros24** [comment]
> Sólo se podrá permitir el uso del sistema a empleados previamente identificados utilizando algún método seguro.

Esto se refiere a la autenticación de los empleados en el sistema y el registro de los movimientos y/o procesos efectuados?

**Comment by estebanz01** [comment]
Hace referencia al inicio de sesión.

Esteban Zapata Rojas.
@estebanz01 - twitter/github

________________________________

**Comment by Tartaros24** [comment]
Registro de inicio y fin de turno para cada empleado, automáticamente con el logueo del empleado en la plataforma.

**Comment by Josesof** [comment]
El inventario en bodega debe tener un stock mínimo y máximo de los productos.

**Comment by Tartaros24** [comment]
Registro de los proveedores existentes y su respectiva información.

**Comment by Tartaros24** [comment]
Informes diarios, semanales, quincenales y mensuales de las ventas, inventario, pagos y facturación.

**Comment by Josesof** [comment]
El sistema debe ser capas de devolver una venta y afectar todo lo que este amarrado a dicha venta.

**Comment by Josesof** [comment]
El sistema de ser capaz de generar alertas de pendiendo de las actividades que este realizando el usuario de la aplicación.

**Comment by Josesof** [comment]
El sistema debe permitir cambiar los roles de los empleados en los casos que sean necesarios.
