### ISSUE TITLE
Análisis y registro de posibles riesgos

### ISSUE THREAD

**Issue by Tartaros24** [zetadevelopment/PMZ_Software#8]
Es necesario establecer cuales son los posibles riesgos a los que nos enfrentamos en la ejecución del proyecto.

Es necesario tenerlos claros para evitar, errores, fallos y/o sobre costos en la ejecución del proyecto.

**Comment by Tartaros24** [comment]
**Posibles riesgos a tener en cuenta dentro de la ejecución del proyecto.**

1. Uno o más de los integrantes no puede cumplir con su gestión.
2. Perdida de información en las BD de los procesos y/o procedimientos en la organización.
3. Pérdida de inventario por cuestiones de vencimiento.
4. Ingreso al sistema de personal no autorizado.
5. La falsificación de la información por parte de los empleados.
6. Robo de inventario.
7. Desastre natural.
8. Regulaciones y normas.
9. Sobre costo no anticipables.

**Acciones para mitigar los riesgos**

1. Dividir su carga laboral entre los demás integrantes operativos.
2. Realizar Backup's de las BD Diaria, Semanal y mensual.
3. Generar alertas en el sistema de las fechas de caducidad de los productos para implementar procesos de promoción y venta y eliminar el stock con esa característica.
4. Tener para cada integrante de la empresa un usuario y una contraseña intransferible, además de un sistemas de log's con las conexiones, movimientos y procesos realizados con cada usuario.
5. Tener estatutos o acuerdos legales dentro de la empresa que garanticen que la información suministrada por el usuario y el empleado sean las correctas, adicional tener métricas de confirmación de la veracidad de la información.
6. Control de los productos y los movimientos que se hagan con cada uno, adicional bodega debe tener un sistema cerrado de cámaras para su vigilancia y control.
7. Realizar Backup's de las BD Diaria, Semanal y mensual.
8. Mantenerse al día con este tipo de regulaciones y en el caso de ser necesario haber negociado previamente con el cliente los cambios a los que haya lugar.
9. Tener un nivel considerable de holgura en los presupuestos necesarios para la ejecución del proyecto.

**Comment by Tartaros24** [comment]
Una vez se recopilen todos los posibles riesgos se plantearan las alternativas necesarias para mitigar dichos riesgos.

**Comment by estebanz01** [comment]
Un posible riesgo es la falsificación de la información por parte de los empleados o la pérdida de inventario por cuestiones de vencimiento.
